### ISSUE TITLE
Update crystalg in README

### ISSUE THREAD

**Issue by vladfaust** [mettuaditya/graphlb#1]
Currently you have

```yaml
dependencies:
  crystalg:
    github: mettuaditya/graphlb
```

in your README. But the correct one is

```diff
dependencies:
-  crystalg:
+  graphlb:
    github: mettuaditya/graphlb
```
